Repository WildCodeSchool-2024-09/JS-RemoteFR-Crew404-P2-WatchYourMood, pull requests merged in 2024-11, with the labels that each got.

#3 acceuil sp 01 modif
  client/src/App.css
  client/src/App.tsx
  client/src/assets/images/colere.png
  client/src/assets/images/joie.png
  client/src/assets/images/peur.png
  client/src/assets/images/tristesse.png
  client/src/components/Avatar.tsx
  client/src/main.tsx
Labels: CONFLICTS

#12 add contact from css
  client/index.html
  client/src/App.css
  client/src/App.tsx
  client/src/components/ContactForm.css
  client/src/components/ContactForm.tsx
  client/src/components/Footer.tsx
  client/src/main.tsx
  client/src/pages/Contact.tsx
Labels: CONFLICTS_RESOLVED

#26 Verso movies
  client/src/components/Header.css
  client/src/components/Movies.css
  client/src/components/Navbar.tsx
  client/src/components/Search.tsx
  client/src/main.tsx
  client/src/pages/Base-globale.tsx
  client/src/pages/Contact.tsx
  client/src/pages/MyMood.css
  client/src/pages/MyMood.tsx
Labels: CORRECTIONS_DONE
